# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PowerTools-Data
version:      0.02
version_from: lib/PowerTools/Data.pm
installdirs:  site
requires:
    DBI:                           DBD::mysql
    Time::HiRes:                   Config::IniHash
    Time::Piece:                   Time::Piece::MySQL

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
